clip:
  step_size: 30
  window_size: 75
datasets:
  nyt_full: ./../doc2img_data/nyt.csv
  nyt_mini: ./../mini_dataset/nyt.csv
  poems_full: ./../doc2img_data/poems
  poems_mini: ./../mini_dataset/poems
  stories_full: ./../doc2img_data/stories
  stories_mini: ./../doc2img_data/stories
  type: poems
device: cuda:0
image_generation:
  inference_steps: 50
  model_id: runwayml/stable-diffusion-v1-5
  save_flag: true
  save_folder: experiment_bart_poems
  seed: 1024
prompts:
- ''
- 'A high resolution photo of '
- 'An image illustrating '
- 'Create an image inspired by '
- 'Generate an artistic interpretation of the text '
- 'Imagine an illustration that captures the central theme of the text '
- 'A realistic image of '
- 'Create an abstract artwork captures the essence of the following: '
summarization:
  max_length: 50
  max_tokens: 50
  min_length: 5
  model: sshleifer/distilbart-cnn-12-6
  no_clusters: 10
summary_method: hf
