datasets:
    poems_mini: ./../mini_dataset/poems
    poems_full: ./../../doc2img_data/poems
    nyt_mini: ./../mini_dataset/nyt.csv
    nyt_full: ./../../doc2img_data/nyt.csv
    
image_generation:
     save_folder: experiment_2
     save_flag: True
     model_id: runwayml/stable-diffusion-v1-5
     seed: 1024
     inference_steps: 5
     
summary_method: tfidf # hf

summarization:
    model : sshleifer/distilbart-cnn-12-6
    min_length: 5
    max_length: 50
    max_tokens: 75