datasets:
    poems: ./../mini_dataset/poems
    nyt: ./../mini_dataset/nyt.csv # small
    #nyt: ./../doc2img_data/nyt.csv # original
    
image_generation:
     save_folder: experiment_2
     save_flag: True
     model_id: runwayml/stable-diffusion-v1-5
     seed: 1024
     inference_steps: 5
     
summary_method: hf

summarization:
    model : sshleifer/distilbart-cnn-12-6
    min_length: 5
    max_length: 50
    max_tokens: 6